model: GNNModel
args:
    in_features: 4096
    hidden_size: 32
    out_size: 10
    gnn_conv: GATv2Conv
    gnn_conv_args:
        # GAT
        heads: 3
        concat: False
        edge_dim: 1

        # GatedGraph
        num_layers: 2
    layers: 2
    dropout: 0.4