train:
    dataset_class: CIFAR10EmbeddedDataset
    base_dir: data/CIFAR10Embeddings/cifar10_train_embeddings.npy
test:
    dataset_class: CIFAR10EmbeddedDataset
    base_dir: data/CIFAR10Embeddings/cifar10_test_embeddings.npy