program: train_model.py
name: CNNVAE_arch_optimization_v1
method: grid
metric:
    goal: minimize
    name: test_loss
parameters:
    in_channels:
        value: 3
    latent_size:
        values: [364, 256, 128, 64, 32, 16, 8]
    block_1:
        values: [1, 2, 3, 4, 5]
    block_2:
        values: [1, 2, 3, 4, 5]
    block_3:
        values: [1, 2, 3, 4, 5]
